# conda env create --file environment.yml
# mamba env create --file environment.yml
name: riesgo_credito
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - plotly
  - python=3.12
  - seaborn
  - scikit-learn
